# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\learn-surveying-software-designing\大地主题解算\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 358)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEdit_B1 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_B1.setGeometry(QtCore.QRect(60, 70, 113, 20))
        self.lineEdit_B1.setObjectName("lineEdit_B1")
        self.lineEdit_L1 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_L1.setGeometry(QtCore.QRect(60, 120, 113, 20))
        self.lineEdit_L1.setObjectName("lineEdit_L1")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 16, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_L2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_L2.setGeometry(QtCore.QRect(220, 120, 113, 20))
        self.lineEdit_L2.setObjectName("lineEdit_L2")
        self.lineEdit_B2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_B2.setGeometry(QtCore.QRect(220, 70, 113, 20))
        self.lineEdit_B2.setObjectName("lineEdit_B2")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(70, 40, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(250, 40, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_S = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_S.setGeometry(QtCore.QRect(140, 190, 191, 21))
        self.lineEdit_S.setObjectName("lineEdit_S")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(40, 190, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_A12 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_A12.setGeometry(QtCore.QRect(140, 230, 191, 21))
        self.lineEdit_A12.setObjectName("lineEdit_A12")
        self.lineEdit_A21 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_A21.setGeometry(QtCore.QRect(140, 270, 191, 21))
        self.lineEdit_A21.setObjectName("lineEdit_A21")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(40, 230, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(40, 270, 71, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 390, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionclose)
        self.menu_2.addAction(self.action_1)
        self.menu_2.addAction(self.action_2)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.actionclose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "B"))
        self.label_2.setText(_translate("MainWindow", "L"))
        self.label_4.setText(_translate("MainWindow", "P1"))
        self.label_5.setText(_translate("MainWindow", "P2"))
        self.label_6.setText(_translate("MainWindow", "大地线长度S"))
        self.label_7.setText(_translate("MainWindow", "正方位角A12"))
        self.label_8.setText(_translate("MainWindow", "反方位角A21"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "大地主题解算"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.action_1.setText(_translate("MainWindow", "正算"))
        self.action_2.setText(_translate("MainWindow", "反算"))
        self.actionclose.setText(_translate("MainWindow", "关闭"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
