# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\learn-surveying-software-designing\坐标换算\mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(574, 771)
        Dialog.setSizeGripEnabled(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 360, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 360, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 160, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(290, 50, 81, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_Open = QtWidgets.QPushButton(Dialog)
        self.pushButton_Open.setGeometry(QtCore.QRect(50, 360, 75, 23))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.pushButton_Save = QtWidgets.QPushButton(Dialog)
        self.pushButton_Save.setGeometry(QtCore.QRect(150, 360, 75, 23))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 480, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 450, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(200, 450, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 54, 12))
        self.label_7.setObjectName("label_7")
        self.pushButton_Close = QtWidgets.QPushButton(Dialog)
        self.pushButton_Close.setGeometry(QtCore.QRect(480, 660, 75, 23))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.plainTextEdit_Input = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_Input.setGeometry(QtCore.QRect(40, 180, 231, 151))
        self.plainTextEdit_Input.setObjectName("plainTextEdit_Input")
        self.plainTextEdit_Out = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_Out.setGeometry(QtCore.QRect(320, 180, 221, 151))
        self.plainTextEdit_Out.setObjectName("plainTextEdit_Out")
        self.lineEdit_l = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_l.setGeometry(QtCore.QRect(50, 480, 113, 20))
        self.lineEdit_l.setObjectName("lineEdit_l")
        self.lineEdit_s = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_s.setGeometry(QtCore.QRect(180, 480, 201, 21))
        self.lineEdit_s.setObjectName("lineEdit_s")
        self.lineEdit_a = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_a.setGeometry(QtCore.QRect(280, 80, 101, 20))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(50, 80, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(410, 50, 54, 12))
        self.label_8.setObjectName("label_8")
        self.lineEdit_alpha = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(410, 80, 131, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(60, 540, 54, 12))
        self.label_9.setObjectName("label_9")
        self.lineEdit_Xangle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Xangle.setGeometry(QtCore.QRect(90, 590, 113, 20))
        self.lineEdit_Xangle.setObjectName("lineEdit_Xangle")
        self.lineEdit_Yangle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Yangle.setGeometry(QtCore.QRect(90, 620, 113, 20))
        self.lineEdit_Yangle.setObjectName("lineEdit_Yangle")
        self.lineEdit_Zangle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Zangle.setGeometry(QtCore.QRect(90, 650, 113, 20))
        self.lineEdit_Zangle.setObjectName("lineEdit_Zangle")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 570, 211, 131))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(250, 540, 54, 12))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(50, 590, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(50, 620, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(50, 650, 31, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 620, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2.setBuddy(self.plainTextEdit_Input)
        self.label_3.setBuddy(self.plainTextEdit_Out)

        self.retranslateUi(Dialog)
        self.pushButton_Close.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox, self.lineEdit_a)
        Dialog.setTabOrder(self.lineEdit_a, self.lineEdit_alpha)
        Dialog.setTabOrder(self.lineEdit_alpha, self.plainTextEdit_Input)
        Dialog.setTabOrder(self.plainTextEdit_Input, self.plainTextEdit_Out)
        Dialog.setTabOrder(self.plainTextEdit_Out, self.pushButton_Open)
        Dialog.setTabOrder(self.pushButton_Open, self.pushButton_Save)
        Dialog.setTabOrder(self.pushButton_Save, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.lineEdit_l)
        Dialog.setTabOrder(self.lineEdit_l, self.lineEdit_s)
        Dialog.setTabOrder(self.lineEdit_s, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_Close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "坐标转换"))
        self.label.setText(_translate("Dialog", "坐标转换工具"))
        self.pushButton.setText(_translate("Dialog", "B,L,H 转 X,Y,Z"))
        self.pushButton_2.setText(_translate("Dialog", "X,Y,Z 转 B,L,H"))
        self.label_2.setText(_translate("Dialog", "输入(&I)"))
        self.label_3.setText(_translate("Dialog", "输出(&O)"))
        self.label_4.setText(_translate("Dialog", "椭球半径a"))
        self.pushButton_Open.setText(_translate("Dialog", "从文件打开"))
        self.pushButton_Save.setText(_translate("Dialog", "保存到文件"))
        self.pushButton_3.setText(_translate("Dialog", "计算平行圈弧长"))
        self.label_5.setText(_translate("Dialog", "l\'\'"))
        self.label_6.setText(_translate("Dialog", "平行圈弧长"))
        self.label_7.setText(_translate("Dialog", "选择椭球"))
        self.pushButton_Close.setText(_translate("Dialog", "关闭程序"))
        self.comboBox.setItemText(1, _translate("Dialog", "WGS-84椭球体"))
        self.comboBox.setItemText(2, _translate("Dialog", "2000中国大地坐标系"))
        self.comboBox.setItemText(3, _translate("Dialog", "1975年国际椭球体"))
        self.label_8.setText(_translate("Dialog", "扁率α"))
        self.label_9.setText(_translate("Dialog", "欧勒角"))
        self.label_10.setText(_translate("Dialog", "变换结果"))
        self.label_11.setText(_translate("Dialog", "εx"))
        self.label_12.setText(_translate("Dialog", "εy"))
        self.label_13.setText(_translate("Dialog", "εz"))
        self.pushButton_4.setText(_translate("Dialog", "旋转变换"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
